version: "3.8"

services:
  spring-backend:
    image: minjin0610/moai-spring-backend:latest
    container_name: moai-spring-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  fast-api-chatbot:
    image: minjin0610/moai-fast-api-chatbot:latest
    container_name: moai-fast-api-chatbot
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
