name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu
          if [ ! -d "infra-deploy" ]; then
            git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/AI-LifeLog-Diary/moia-deploy.git
          fi
          cd infra-deploy
          git pull origin main
          docker-compose pull
          docker-compose up -d

